### PR TITLE
Reader rewrite

### PR DESCRIPTION
**Pull request by maasha**
Let's get this sucker merged. However, give the code a good review to spot possible slowdowns (missing pass by reference and such). Copy constructors and such can be introduced later on a need to basis.

### CODE REVIEW

**Comment by ahovgaard** [comment]
I just noticed you added `-O3`. Did we try with `-march=native` yet?
Might be more interesting for other things than IO though.

**Comment by ahovgaard** [comment]
In `test_read_buffer.cc` line 70, what is

``` cpp
REQUIRE_FALSE(rb.PrevChar());
```

supposed to mean? That it is equal to '\0'?

**Comment by maasha** [comment]
I have no idea what -march=native does :oD.

Returning '\0' is used to signal that rb.PrevChar() failed.

**Comment by ahovgaard** [comment]
`-march=native` will let the compiler generate newer instructions (e.g. `POPCNT` for efficient bitset counting of set bits) which are supported on the current machine architecture. I think the compiler will be more conservative otherwise. It seems that it is only supported on GNU/Linux with g++, but I don't know about clang.

**Comment by ahovgaard** [comment]
Buffers in `FastaReader` were not being deallocated. There is still some memory leak as can be seen using valgrind and if I try to delete `buffer_` in the ReadBuffer destructor, some test fails:

```
-------------------------------------------------------------------------------
FastaReader w. empty file throws
-------------------------------------------------------------------------------
/home/akh/uni/BIO-DIKU/BioIO/test/test_fasta_reader.cc:172
...............................................................................

/home/akh/uni/BIO-DIKU/BioIO/test/test_fasta_reader.cc:184: FAILED:
  REQUIRE( e.exceptionMsg == "Error: missing sequence name" )
with expansion:
  "Error: missing sequence"
  ==
  "Error: missing sequence name"
```

**Comment by maasha** [comment]
So is it important to deallocate these buffers? I meant them to be kept
around until the program terminates - maybe I have offended some
programming God?.

**Comment by ahovgaard** [comment]
They will be kept around as long as you have a `FastaReader` object.

That's quite possible :smiley: but at least the buffers just hang around until termination and the memory leak doesn't grow.

**Comment by maasha** [comment]
If we deallocate the buffers in the destructor, the gods will be pleased?

**Comment by ahovgaard** [comment]
Yes because the destructor will be called when the `FastaReader` object is deallocated. Of course, if `FastaReader` is kept around during the whole execution, then it doesn't really make a difference, but it's better to be explicit about memory deallocation than rely on the OS cleaning up on termination.

If you run valgrind, you'll see:

``` valgrind
==17242== LEAK SUMMARY:
==17242==    definitely lost: 300,670,720 bytes in 17 blocks
```

Doesn't look so good. :)

**Comment by AndreasDahl** [comment]
You could probably use `unique_ptr`s instead of explicit delete.

**Comment by maasha** [comment]
Feel free to include nifty C++ tricks! As long as there is no slow-down ...

**Comment by AndreasDahl** [comment]
I'll look at it if i get time. I'm pretty busy putting out fires at work at the moment though.

**Comment by maasha** [comment]
We could use a merge of this (and polish issues later) - a similar
FastqReader is ready within the hour.

**Comment by AndreasDahl** [comment]
I do not think we should merge a known memory leak. It may come back to haunt us later if we forget it.

**Pull request merged**
